name: Test
on: push


concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        rabbit-version:
          - "rabbitmq:3.7"
          - "rabbitmq:3.8"
          - "rabbitmq:3.9"

    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-lein-2.9.6
    services:
      rabbitmq:
        image: ${{ matrix.rabbit-version }}
        env:
          RABBITMQ_DEFAULT_USER: rabbit
          RABBITMQ_DEFAULT_PASS: password
          RABBITMQ_DEFAULT_VHOST: /main
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl node_health_check"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: /home/runner/.m2
        key: v1-deps-${{ hashFiles('project.clj') }}
        restore-keys: |
          v1-deps-${{ hashFiles('project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests for ${{ matrix.rabbit-version }}
      id: tests
      run: lein test 2>&1
      env:
        RABBIT_URL: amqp://rabbit:password@rabbitmq:5672
        RABBIT_VHOST: /main
